version: "3"
name: todos

services:
  api:
    build: 
      context: "."
    restart: "unless-stopped"
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    networks: [ todos ]

networks:
  todos:
    driver: bridge
